[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
roxido = { path="roxido" }
lapjv = "0.2.0"
ndarray = "0.15.4"
rand = "0.8.4"
rand_pcg = "0.3.1"
rayon = "1.5.1"
