[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
roxido = { path="roxido" }
lapjv = "0.2.0"
ndarray = "0.13.1"
rand = "0.8.3"
rand_pcg = "0.3.0"
rayon = "1.5.1"
